#!/bin/bash
# Initramfs Post-Update hook to generate boot.img inside /boot
set -eo pipefail

version="$1"
if [[ -z "$version" ]]; then
	echo >&2 "W: rpi-boot-img: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

RPI_CONFIG_FILE=/etc/initramfs/rpi-config.txt
RPI_CMDLINE_FILE=/etc/initramfs/rpi-cmdline.txt
BOOT_IMG=/boot/boot.img
BOOT_IMG_SIZE=32  # MB
BOOT_MOUNTPOINT=/tmp/rpi-boot-img

# read config vars
source /etc/initramfs/rpi-vars.sh

echo "Running RPI ramdisk generator for version $version..."

dd if=/dev/zero bs=1M count=$BOOT_IMG_SIZE of="$BOOT_IMG"
losetup /dev/loop8 "$BOOT_IMG"
# close the loop device on every exit status using a trap
cleanup() {
	set +e
	umount /dev/loop8
	losetup -d /dev/loop8
}
trap 'cleanup' EXIT

# Format the boot img partition as FAT32
mkfs.vfat -n RPI_BOOT_RD /dev/loop8
mkdir -p "$BOOT_MOUNTPOINT"
mount /dev/loop8 "$BOOT_MOUNTPOINT"

install "/boot/vmlinuz-$version" "$BOOT_MOUNTPOINT/kernel8.img"
install "/boot/initrd.img-$version" "$BOOT_MOUNTPOINT/initrd.img"
for file in "${RPI_FIRMWARE_FILES[@]}"; do
	if [[ "$file" == "/"* ]]; then
		# absolute path, copy it
		cp -f "$file" "$BOOT_MOUNTPOINT/$(basename "$file")"
	else
		# download the latest rpi firmware files (debian repo is outdated)
		wget "https://github.com/raspberrypi/firmware/raw/master/boot/$file" \
			-O "$BOOT_MOUNTPOINT/$file"
	fi
done

RPI_CONFIG=$(cat "$RPI_CONFIG_FILE")
RPI_CMDLINE=$(cat "$RPI_CMDLINE_FILE" | head -1)
[[ -z "$RPI_CONFIG_EXTRA" ]] || RPI_CONFIG+="
$RPI_CONFIG_EXTRA"
[[ -z "$RPI_CMDLINE_EXTRA" ]] || RPI_CMDLINE+=" $RPI_CMDLINE_EXTRA"
echo "$RPI_CONFIG" > "$BOOT_MOUNTPOINT/config.txt"
echo "$RPI_CMDLINE" > "$BOOT_MOUNTPOINT/cmdline.txt"
# cat "$BOOT_MOUNTPOINT/config.txt"
# cat "$BOOT_MOUNTPOINT/cmdline.txt"

echo "RPI boot ramdisk '$BOOT_IMG' successfull generated!"
ls -lh "$BOOT_MOUNTPOINT"

exit 0

