#!/bin/bash
# Initramfs Post-Update hook to generate boot.img inside /boot
set -eo pipefail
source /usr/local/lib/rpi-debian-scripts.sh

version="$1"
if [[ -z "$version" ]]; then
	echo >&2 "W: rpi-boot-img: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

RPI_CONFIG_FILE=/etc/initramfs/rpi-config.txt
RPI_CONFIG_RAW_FILE=/etc/initramfs/rpi-config-raw.txt
RPI_CMDLINE_FILE=/etc/initramfs/rpi-cmdline.txt
BOOT_IMG=/boot/boot.img
BOOT_IMG_SIZE=32  # MB
BOOT_MOUNTPOINT=/tmp/rpi-boot-img

# read config vars
source /etc/initramfs/rpi-vars.sh

RPI_CONFIG=$(cat "$RPI_CONFIG_FILE")
RPI_CONFIG_RAW=$(cat "$RPI_CONFIG_RAW_FILE")
RPI_CMDLINE=$(cat "$RPI_CMDLINE_FILE" | head -1)
[[ -z "$RPI_CONFIG_EXTRA" ]] || RPI_CONFIG+="
$RPI_CONFIG_EXTRA"
[[ -z "$RPI_CMDLINE_EXTRA" ]] || RPI_CMDLINE+=" $RPI_CMDLINE_EXTRA"

INTERPOLATE_VARS=(
	"ROOTFS_PARTITION=LABEL=$IMAGE_ROOTFS_PART_NAME"
)

function download_firmware_files() {
	for file in "${RPI_FIRMWARE_FILES[@]}"; do
		if [[ "$file" == "/"* ]]; then
			# absolute path, copy it
			cp -f "$file" "$1/$(basename "$file")"
		else
			# download the latest rpi firmware files (debian repo is outdated)
			wget "https://github.com/raspberrypi/firmware/raw/master/boot/$file" \
				-O "$1/$file"
		fi
	done
}

if [[ -n "$RPI_SKIP_IMAGE_GEN" ]]; then
	# save config.txt to /boot
	mkdir -p /boot/firmware
	download_firmware_files "/boot/firmware"
	interpolate_vars "$RPI_CONFIG" "${INTERPOLATE_VARS[@]}" > "/boot/firmware/config.txt"
	exit 0
fi

echo "Running RPI ramdisk generator for version $version..."

dd if=/dev/zero bs=1M count=$BOOT_IMG_SIZE of="$BOOT_IMG"
losetup /dev/loop8 "$BOOT_IMG"
# close the loop device on every exit status using a trap
cleanup() {
	set +e
	umount /dev/loop8
	losetup -d /dev/loop8
}
trap 'cleanup' EXIT

# Format the boot img partition as FAT32
mkfs.vfat -n RPI_BOOT_RD /dev/loop8
mkdir -p "$BOOT_MOUNTPOINT"
mount /dev/loop8 "$BOOT_MOUNTPOINT"

install "/boot/vmlinuz-$version" "$BOOT_MOUNTPOINT/kernel8.img"
install "/boot/initrd.img-$version" "$BOOT_MOUNTPOINT/initrd.img"
download_firmware_files "$BOOT_MOUNTPOINT/"

interpolate_vars "$RPI_CONFIG" "${INTERPOLATE_VARS[@]}" > "$BOOT_MOUNTPOINT/config.txt"
interpolate_vars "$RPI_CONFIG_RAW" "${INTERPOLATE_VARS[@]}" > "/boot/config-raw.txt"
interpolate_vars "$RPI_CMDLINE" "${INTERPOLATE_VARS[@]}" > "$BOOT_MOUNTPOINT/cmdline.txt"
# cat "$BOOT_MOUNTPOINT/config.txt"
# cat "$BOOT_MOUNTPOINT/cmdline.txt"

echo "RPI boot ramdisk '$BOOT_IMG' successfull generated!"
ls -lh "$BOOT_MOUNTPOINT"

exit 0

